import { Geist, Geist_Mono, Saira } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
 

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const saira = Saira({
  variable: "--font-saira",
  subsets: ["latin"]
})

export const metadata = {
  title: "AniKomi - Explore Your Interesting Animes",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${saira.className} antialiased tracking-wider`}
        >
        <Navbar/>
          {children}
      </body>
    </html>
  );
}
